import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "@/(Components)/BootstrapClient";

const publicSans = Public_Sans({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.className} `}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
